### ISSUE TITLE
pretrained fbvideo model

### ISSUE THREAD

**Issue by AnanS** [facebook/C3D#1]
Great paper, thanks for making the source code available! Is the pretrained fbvideo model (that corresponds to the prototxt "c3d_fbvideo_feature_extractor_frm/video.prototxt") made available as well?

**Comment by dutran** [comment]
@AnanS: thank for your interests in our work. As mentioned in the project page. c3d_sport1m gives much better performance (accuracy) compared with c3d_fbvideo. Thus, we decide to publish only c3d_sport1m, so that not confuse the users.

For general questions, please feel free to email me (or the other authors). We prefer to keep this place for posting issues related to C3D code/software.
