### ISSUE TITLE
visualize the feature

### ISSUE THREAD

**Issue by learntolearn11** [facebook/C3D#100]
have anyone used the DeconvNetToolbox to visualize the feature ? I see the introduce of theDeconvNetToolbox . it need to train the model and reconstruct the model, while if you have trained the model by the caffe, do you need re-train it using the DeconvNetToolbox? I would greatly appreciate it if anyone can let me know detail of  visualizing the the features. Thanks a lot.

**Comment by dutran** [comment]
@learntolearn11 I have got quite a few emails for this part of code. I did not want to share because it is currently a little bit hacky (I got it done one or two days before the deadline). I will feel very embarrassing to show/share those kind of code to everyone. Unfortunately, for now I cannot have any time to revise it in a proper/descend form.
