### ISSUE TITLE
Cannot open the frames of the pre-trained model sports1m

### ISSUE THREAD

**Issue by rohitqut** [facebook/C3D#105]
Hello,
While installing C3D, following error is coming when I put the command 'sh c3d_sport1m_feature_extraction_frm.sh or sh c3d_sport1m_feature_extraction_video.sh'

E0408 14:52:21.138438  6888 common.cpp:31] Cannot create Cublas handle. Cublas won't be available.
E0408 14:52:21.138808  6888 common.cpp:38] Cannot create Curand generator. Curand won't be available.
F0408 14:52:21.138968  6888 common.cpp:68] Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version

NOTE: I have CUDA 7.5 version installed.

**Comment by dutran** [comment]
@rohitqut are you running it on a machine with GPU(s)?

**Comment by rohitqut** [comment]
@dutran No. I am running it without GPU.

**Comment by dutran** [comment]
Then you have to modify 
GLOG_logtosterr=1 ../../build/tools/extract_image_features.bin prototxt/c3d_sport1m_feature_extractor_frm.prototxt conv3d_deepnetA_sport1m_iter_1900000 0 50 1 prototxt/output_list_prefix.txt fc7-1 fc6-1 prob

to this

GLOG_logtosterr=1 ../../build/tools/extract_image_features.bin prototxt/c3d_sport1m_feature_extractor_frm.prototxt conv3d_deepnetA_sport1m_iter_1900000 -1 50 1 prototxt/output_list_prefix.txt fc7-1 fc6-1 prob

GPU ID = -1 instead of 0. Otherwise you will get CUDA device error.

**Comment by rohitqut** [comment]
@dutran Thanx du. It worked to some extent. At one point, the following error came.
F0409 02:40:53.853106  8714 io.cpp:56] Check failed: fd != -1 (-1 vs. -1) File not found: conv3d_deepnetA_sport1m_iter_1900000

Unable to figure out the reason! Kindly help.

**Comment by dutran** [comment]
@rohitqut you did not download the pre-trained model

**Comment by rohitqut** [comment]
Thanx du. I hope there would not be any issues with running video file now.

**Comment by rohitqut** [comment]
@dutran Thanx.
