### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by Michael-Guo** [facebook/C3D#12]
Dear dutran! 
When I run c3d_sport1m_feature_extraction_frm.sh, I always get an error: out of memory.  Although I reduce the bath-size to 10, 5 even to 1, the error appears again and again.
My GPU's memory is 1GB, is it two small for this exxample?
Thanks a lot!

**Comment by dutran** [comment]
1GB is too small for C3D network. C3D had been tested on K40 (12GB) and K20 (6GB) with reduced mini batch size. If you further reduce to minimum batch-size, you still need around 3GB.

However, if you use mini batch size 1, there will be not much advantage from using GPU (compared to CPU, technically there is still a little bit better due to the optimized matrix multiplication implementation). Given that your GPU memory is small, you may want try to use CPU instead (please see the User Guide).

**Comment by proact** [comment]
Thank you! 
In my case, while using AWS g2.2xlarge, needed to decrease batch size to 25.
