### ISSUE TITLE
3 questions

### ISSUE THREAD

**Issue by gtln** [facebook/C3D#124]
Hi Du Tran,
Can you please tell me:
1) My input videos are of size 320x240 (UCF101) and these videos are resized to 171x128 by the C3D.  Should I use width=320 or 171 and height=240 or 128 as an input to compute_volume_mean_from_list?
2) What are the smallest videos (spatial resolution) that this network and c3d_ucf101_finetuning_train.prototxt can work with?
3) Can this network and c3d_ucf101_finetuning_train.prototxt be used to train a dataset with e.g. 1000 classes?
Thanks

**Comment by dutran** [comment]
1) it needs to be 128x171
2) for this pre-trained model (C3D), it works on 16x112x112 inputs. You can have different video resolution inputs, with a constraint that crop size must be 122 (this also imply that smallest resolution you can use is 112x112).
3) Yes, modify fc-8 to 1000 output instead of 487
