### ISSUE TITLE
Compile Problem for C3D-V1.0

### ISSUE THREAD

**Issue by Actl9239** [facebook/C3D#292]
When I tick the commond "cmake.."
the problem is ：
CMake Error: Error in cmake code at
/home/gpu-common/Caffe_C3D/C3D/C3D-v1.0/CMakeLists.txt:5:
Parse error.  Expected "(", got unquoted argument with text ":=".
-- Configuring incomplete, errors occurred!

Can you tell me how to solve it ?

**Comment by dutran** [comment]
@Actl9239 I think you have to modify Makefile.config, then make. Which platform are you on then you compiled?

**Comment by AustinVan** [comment]
Dear dutran,
I saw there was deconv-3d in newest code. Does this layer improve the performance? Do you already have any paper to support this in 3D conv? Or other people's paper. If you have, could you  pls recommend to me.

many thanks

**Comment by dutran** [comment]
It is just simply porting v1.0 de-conv to 1.1.

In [1], we use 3d de-conv, [2] we used 3d-conv.
 
1. Du Tran, Lubomir Bourdev, Rob Fergus, Lorenzo Torresani, and Manohar Paluri, Deep End2End Voxel2Voxel Prediction, The 3rd Workshop on Deep Learning in Computer Vision 2016.
2. Du Tran, Lubomir Bourdev, Rob Fergus, Lorenzo Torresani, and Manohar Paluri, Learning Spatiotemporal Features with 3D Convolutional Networks, ICCV 2015.

**Comment by AustinVan** [comment]
Duran：
Thanks for your reply.
Actually, I have designed a hardware accelerator for you C3D.
My papar will publish on FPL, 2017 (top conference in FPGA filed) in Sep. Welcome to read and give comments. ^_^

Now I am evaluating your V2V proposed in your paper, Deep End2End Voxel2Voxel Prediction, and considering to design corresponding accelerator for your V2V
I have few questions:
1. In result part of video segmentation, you only proved that your network is better than 2D-V2V and you design is optimal(because you only campare V2V with V2V-skip and Conv-Up, all of these network are designed by yourself). Did you compare your network with mainstreaming video segmentation networks or algorithms?
2.I have also read the paper about GATECH dataset,  Geometric context from video.  In that paper, there is no result about the video segmentation accuracy. Did you test your network on other mainstreaming dataset with accuracy result.

Sincerely you can help me.

**Comment by dutran** [comment]
@AustinVan 
1. Back to the time of V2V, most of mainstream semantic segmentation work are on images, not on videos. Thus, GATECH was the only dataset. I had to compare it with baselines (designed my myself) instead. I no longer work on semantic segmentation after that, not sure what is the status for now.
2. Yes, the original provided number of classification accuracy on superpixel and with two-level of taxonomies.

Feel free to send me your paper, I am happy to read and provide comments.
Thanks
