### ISSUE TITLE
Issues about computing the volume mean file

### ISSUE THREAD

**Issue by csyizhou** [facebook/C3D#30]
Hi everyone, 

Now I'd like to train on my own data from scratch.  I can start the training without the mean file, but get the error as attached image when I use the mean file.
![image](https://cloud.githubusercontent.com/assets/11431911/9955354/2e0f9050-5de8-11e5-92dc-8b29039ef202.png)

I guess the problem comes from the volume mean file. I run the 'compute volume mean from list.bin', it seems ok as attached image, 
![image](https://cloud.githubusercontent.com/assets/11431911/9955376/601ef73e-5de8-11e5-8783-cb35446a5470.png)

but processing speed is too fast only 3seconds and the generated *_mean.binartproto file is very small only 10 bytes.

The image below is my input_chunk_list.
![image](https://cloud.githubusercontent.com/assets/11431911/9955390/899cadfe-5de8-11e5-8f6b-86a2ac8b9737.png)

Could you give me some help? Thanks a lot!

**Comment by dutran** [comment]
Your mean file is empty. You either got:
1) wrong relative path to .avi (in the list file)
or
2) the path is correct, but your opencv is not compiled correctly with --enable-shared flag with ffmpeg, so I/O function to read .AVI does not work properly.

In both case, I/O did not actually happen, that why computing mean is done quickly because no clip was actually loaded.

**Comment by dutran** [comment]
@csyizhou Have you solved your problem?

**Comment by csyizhou** [comment]
@dutran thanks very much, your second suggestion help me solve the problem.
