### ISSUE TITLE
compilation error at math_functions.cu(140)

### ISSUE THREAD

**Issue by escorciav** [facebook/C3D#60]
Hi,

I got the following error trying to compile C3D with CUDA 6.5  and 7.0. Does anyone know if it is related with the CUDA version?
```
src/caffe/util/math_functions.cu(140): error: calling a __host__ function("std::signbit<float> ") from a __global__ function("caffe::sgnbit_kernel<float> ") is not allowed

src/caffe/util/math_functions.cu(140): error: calling a __host__ function("std::signbit<double> ") from a __global__ function("caffe::sgnbit_kernel<double> ") is not allowed

2 errors detected in the compilation of "/tmp/tmpxft_0000a101_0000000013_math_functions.compute_35.cpp1.ii".
make: *** [build/src/caffe/util/math_functions.cuo] Error 2
```
If it's not cuda version, any hint?
 I'm downloading CUDA 5.5 recommended for the caffe commit used for C3D. I will come back with my conclusion.

**Comment by escorciav** [comment]
[This answer](http://stackoverflow.com/a/29021849/1319193) solved my problem. I don't know the cause but it seems that it's not related with the version of CUDA.

**Comment by haohao900618** [comment]
Hi @escorciav, I encountered the same problem as yours, and I follow the answer http://stackoverflow.com/questions/28985551/caffe-installation-in-ubuntu-14-04/29021849#29021849 solveed the error. When I run train_ucf101.sh without any modification, but I got the accuracy around 0 and the loss around 4.6 aways. The later problem maybe caused by the previous one. I want to know have you  encountered the later problem like me.

**Comment by escorciav** [comment]
I'm sorry but I have no idea how to solve your problem. Indeed, I'm not convinced that it's related with that modification.
My tip: Double and Triple check other parts of your pipeline, ASAMOF finetune a model first. While you are suffering waiting for good results, I would recommend you compile a recent version of gcc >= 4.8 and <= 5. I haven't found this error with a recent version.

BTW, Drop a line if the error was on that line :wink: 
*Disclaimer: I'm a rookie in C++*
